name: Dev Databricks Infra CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  cicd:
    name: Dev Databricks Infra CI/CD
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_BUNDLE_TARGET: e2-demo-field-eng
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: databricks/setup-cli@main
      - name: Validate Bundle
        id: validate
        run: |
          databricks bundle validate 
      - name: Deploy Bundle
        id: deploy
        if: ${{ github.event_name == 'push' }}
        run: |
          databricks bundle deploy
