name: Run code tests
on:
  push
jobs:
  test:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        id: run_tests
        run: echo 'running tests...'
        shell: bash
